name: 01-building-blocks
on: push
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello GitHub Actions"
  echo-myname:
    runs-on: ubuntu-latest
    steps:
      - name: Say Myname
        run: echo "my name is nader"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye
        run: echo "i will leave"
