name: 02-workflows-events
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  echo-event:
    runs-on: ubuntu-latest
    steps:
      - name: show trigger
        run: echo " Hello i have been triggered by ${{ github.event_name }}"
